language: c

git:
  depth: 3

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - sourceline: 'deb https://apt.kitware.com/ubuntu/ ${TRAVIS_DIST} main'
      key_url: 'https://apt.kitware.com/keys/kitware-archive-latest.asc'
    update: true
    packages:
    - gcc-7
    - g++-7
    - cmake
    - libsndfile1-dev
    - libfftw3-dev
    - libfdk-aac-dev
    - libboost-dev
    - libmpg123-dev
    - libmp3lame-dev
    - doxygen
    - graphviz
    - ninja-build
# This fails "/usr/local/bin/brew tap homebrew/bundle": Error: Unknown command: bundle
  homebrew:
    update: true
    packages:
    - ccache
    - cmake
    - ninja
    - mpg123
    - lame
    - libsndfile
    - fdk-aac
    - fftw
    # - boost
    - doxygen
    - graphviz

cache:
  ccache: true

before_install:
- export PATH="${PATH}:${PWD}/deps/build-scripts/bin"
- uname -a
- set -e -o pipefail

install:
- source ci/install-deps.${TRAVIS_OS_NAME}.sh
- source ci/build-deps.sh
- cmake --version

script:
- mkdir -p build && cd build
- cmake ${TARGET_PLATFORM:+-A ${TARGET_PLATFORM}} ${CMAKE_GENERATOR:+"-DCMAKE_GENERATOR=${CMAKE_GENERATOR}"} -DDSPXX_BUILD_DEMOS=ON "-DCMAKE_PREFIX_PATH=${PWD}/deps/install" ..
- cmake --build . --config RelWithDebInfo
- ctest --output-on-failure -C RelWithDebInfo -T test -j3
- cmake --build . --config RelWithDebInfo --target docs
- cmake --build . --config RelWithDebInfo --target package

matrix:
  include:
  - os: osx
    name: macOS 10.14 (10.15 SDK)
    osx_image: xcode11.2
    env: CMAKE_GENERATOR=Ninja
  - os: osx
    name: macOS 10.13 (10.14 SDK)
    osx_image: xcode10.1
    env: CMAKE_GENERATOR=Ninja
  - os: osx
    name: macOS 10.12 (10.13 SDK)
    osx_image: xcode9.2
  - os: linux
    name: Bionic-x64
    dist: bionic
    env: CMAKE_GENERATOR=Ninja
  - os: linux
    name: Xenial-x64
    dist: xenial
    env: CMAKE_GENERATOR=Ninja CC=gcc-7 CXX=g++-7
# TODO: investigate why this fails on travis
#   - os: linux
#     name: Bionic-ARM64
#     dist: bionic
#     arch: arm64
#   - os: linux
#     name: Xenial-ARM64
#     dist: xenial
#     arch: arm64
  - os: windows
    name: Win32
    env: TARGET_PLATFORM=Win32
  - os: windows
    name: Win64
    env: TARGET_PLATFORM=x64
