#! /usr/bin/env bash
set -e -o pipefail
set -x

THIS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
ABIS=(arm64-v8a armeabi-v7a x86 x86_64)
NDK="${NDK:-${HOME}/Android/Sdk/ndk/22.0.7026061}"
API="${API:-21}"
CMAKE="${CMAKE:-${NDK}/../../cmake/3.18.1/bin/cmake}"

function build_single_abi {
    mkdir -p build
    pushd build
    rm -rf CMake*
    "${CMAKE}" \
        -GNinja \
        -DCMAKE_TOOLCHAIN_FILE="${NDK}/build/cmake/android.toolchain.cmake" \
        -DANDROID_ABI="${ABI}" \
        -DANDROID_NATIVE_API_LEVEL="${API}" \
        -DANDROID_ARM_NEON=ON \
        "-DANDROID_CCACHE=$(which ccache)" \
        "-DANDROID_CPP_FEATURES=rtti exceptions" \
        ${BUILT_DEPS_DIR:+"-DCMAKE_FIND_ROOT_PATH=${BUILT_DEPS_DIR}/${ABI}"} \
        "$@" \
        "${THIS_DIR}"
    "${CMAKE}" --build .
    popd
}

for abi in "${ABIS[@]}"
do
    ABI="${abi}" build_single_abi "$@"
done
